# Generated by Django 6.0 on 2025-12-31 05:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("CSE(AI)", "Computer Science & Engineering(AI)"),
                            ("CSE(DS)", "Computer Science & Engineering(DS)"),
                            ("CSE(IOT)", "Computer Science & Engineering(IOT)"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("address", models.CharField(default="Address", max_length=100)),
                ("emp_id", models.IntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("FA", "Faculty"),
                            ("AD", "Admin"),
                            ("SPA", "Superadmin"),
                        ],
                        default="FA",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "Registered"), ("NR", "NotRegistered")],
                        default="NR",
                        max_length=2,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("AP1", "Assistant Professor 1"),
                            ("AP2", "Assistant Professor 2"),
                            ("ASP1", "Associate Professor 1"),
                            ("ASP2", "Associate Professor 2"),
                            ("P", "Professor"),
                        ],
                        default="AP1",
                        max_length=4,
                    ),
                ),
                (
                    "aos",
                    models.CharField(
                        choices=[
                            ("AIML", "Artificial Intelligence & Machine Learning"),
                            ("DIS", "Data & Information Systems"),
                            ("CN", "Cybersecurity & Networks"),
                            ("SSD", "Software Systems & Development"),
                            ("CSA", "Computer Systems & Architecture"),
                            ("M", "Mathematics"),
                            ("TCS", "Theoretical Computer Science"),
                            ("O", "Other"),
                        ],
                        default="O",
                        max_length=4,
                    ),
                ),
                (
                    "hq",
                    models.CharField(
                        choices=[
                            ("BT", "B.E. / B.Tech"),
                            ("MT", "M.E. / M.Tech"),
                            ("MS", "M.S."),
                            ("MBA", "MBA"),
                            ("PHD", "Ph.D."),
                            ("PD", "Post-Doctoral Research (Post-Doc)"),
                            ("O", "Other"),
                        ],
                        default="O",
                        max_length=3,
                    ),
                ),
                ("univ_name", models.CharField(default="Unknown", max_length=100)),
                ("pshd", models.IntegerField(default=0)),
                ("pan_no", models.CharField(default="AAAEE875AE", max_length=10)),
                ("dob", models.DateField(default=datetime.date(1970, 1, 1))),
                ("jd", models.DateField(default=datetime.date(1970, 1, 1))),
                ("pd", models.DateField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to="uploads/faculty_documents/profile_picture",
                    ),
                ),
                (
                    "jr",
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to="uploads/faculty_documents/joining_report/",
                    ),
                ),
                (
                    "of",
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to="uploads/faculty_documents/offer_letter/",
                    ),
                ),
                (
                    "ss",
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to="uploads/faculty_documents/salary_slip/",
                    ),
                ),
                (
                    "hdc",
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to="uploads/faculty_documents/higher_degree_certificate/",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        default=None,
                        null=True,
                        upload_to="uploads/faculty_documents/certificate/",
                    ),
                ),
                ("phd_univ", models.CharField(blank=True, max_length=100, null=True)),
                ("phd_dor", models.DateField(blank=True, null=True)),
                ("norp", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Student_Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "batch",
                    models.CharField(
                        choices=[
                            ("3CS-A", "Cs A"),
                            ("3CS-B", "Cs B"),
                            ("3CS-C", "Cs C"),
                            ("3CS-D", "Cs D"),
                            ("3CS-E", "Cs E"),
                            ("3CS-F", "Cs F"),
                            ("3CS(AI)-A", "Cs Ai A"),
                            ("3CS(AI)-B", "Cs Ai B"),
                            ("3CS(DS)-A", "Cs Ds A"),
                            ("3CS(IOT)-A", "Cs Iot A"),
                            ("3CS(IOT)-B", "Cs Iot B"),
                        ],
                        default="3CS-F",
                        max_length=10,
                    ),
                ),
                ("roll_no", models.CharField(max_length=100)),
                ("college_id", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("student_phone_no", models.CharField(max_length=10)),
                ("parent_phone_no", models.CharField(max_length=10)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FDP", "FDP"),
                            ("WKP", "Workshop"),
                            ("CON", "Conference"),
                            ("STTP", "Sttp"),
                            ("SEM", "Seminar"),
                            ("WEB", "Webinar"),
                            ("LS", "Lecture Series"),
                            ("SYM", "Symposium"),
                            ("EE(UG)", "External  Examination(UG)"),
                            ("EE(PG)", "External  Examination(PG)"),
                            ("JOU", "Journal"),
                            ("EL", "Expert Lecture"),
                            ("ET", "Expert Talk"),
                            ("HAT", "Hackathon"),
                            ("TRA", "Training"),
                            ("INT", "Internship"),
                            ("BOS", "BOS"),
                            ("DRC", "DRC"),
                            ("STC", "Short Term Courses"),
                            ("MOOC", "MOOC courses"),
                            ("IP", "Induction Program"),
                            ("EDU", "Education"),
                            ("REA", "Research"),
                            ("SPO", "Sports"),
                            ("SG", "Sponsored Grant"),
                            ("RP", "Research Project"),
                            ("CONS", "Consultancy"),
                            ("M_TECH", "M.Tech Students"),
                            ("PH_D", "Ph.D Students"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=6,
                    ),
                ),
                (
                    "eof",
                    models.CharField(
                        choices=[
                            ("S", "Students"),
                            ("TS", "Teaching Staff"),
                            ("NTS", "Non-Teaching Staff"),
                        ],
                        max_length=3,
                    ),
                ),
                ("topdpo", models.CharField(max_length=100)),
                ("nop", models.IntegerField()),
                ("adcc", models.CharField(max_length=100)),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "ct",
                    models.CharField(
                        choices=[("S", "Sponsored"), ("NS", "Non-Sponsored")],
                        max_length=2,
                    ),
                ),
                ("nosa", models.CharField(max_length=100)),
                ("cd", models.CharField(max_length=100)),
                ("begi_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "gr",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("gd", models.CharField(max_length=100)),
                ("awpsfooe", models.CharField(max_length=100)),
                ("nossp", models.IntegerField()),
                ("nosmp", models.IntegerField()),
                (
                    "eraipf",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("proof_file", models.FileField(upload_to="uploads/events/")),
                ("remarks", models.CharField(max_length=255, null=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="awards_and_achievments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FDP", "FDP"),
                            ("WKP", "Workshop"),
                            ("CON", "Conference"),
                            ("STTP", "Sttp"),
                            ("SEM", "Seminar"),
                            ("WEB", "Webinar"),
                            ("LS", "Lecture Series"),
                            ("SYM", "Symposium"),
                            ("EE(UG)", "External  Examination(UG)"),
                            ("EE(PG)", "External  Examination(PG)"),
                            ("JOU", "Journal"),
                            ("EL", "Expert Lecture"),
                            ("ET", "Expert Talk"),
                            ("HAT", "Hackathon"),
                            ("TRA", "Training"),
                            ("INT", "Internship"),
                            ("BOS", "BOS"),
                            ("DRC", "DRC"),
                            ("STC", "Short Term Courses"),
                            ("MOOC", "MOOC courses"),
                            ("IP", "Induction Program"),
                            ("EDU", "Education"),
                            ("REA", "Research"),
                            ("SPO", "Sports"),
                            ("SG", "Sponsored Grant"),
                            ("RP", "Research Project"),
                            ("CONS", "Consultancy"),
                            ("M_TECH", "M.Tech Students"),
                            ("PH_D", "Ph.D Students"),
                            ("OTH", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("noaa", models.CharField(max_length=100)),
                ("paf", models.CharField(max_length=100)),
                ("ao", models.CharField(max_length=100)),
                ("prize", models.CharField(max_length=100)),
                ("ad", models.DateField()),
                ("remark", models.CharField(max_length=255, null=True)),
                ("proof_file", models.FileField(upload_to="uploads/awards/")),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty_participation_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FDP", "FDP"),
                            ("WKP", "Workshop"),
                            ("CON", "Conference"),
                            ("STTP", "Sttp"),
                            ("SEM", "Seminar"),
                            ("WEB", "Webinar"),
                            ("LS", "Lecture Series"),
                            ("SYM", "Symposium"),
                            ("EE(UG)", "External  Examination(UG)"),
                            ("EE(PG)", "External  Examination(PG)"),
                            ("JOU", "Journal"),
                            ("EL", "Expert Lecture"),
                            ("ET", "Expert Talk"),
                            ("HAT", "Hackathon"),
                            ("TRA", "Training"),
                            ("INT", "Internship"),
                            ("BOS", "BOS"),
                            ("DRC", "DRC"),
                            ("STC", "Short Term Courses"),
                            ("MOOC", "MOOC courses"),
                            ("IP", "Induction Program"),
                            ("EDU", "Education"),
                            ("REA", "Research"),
                            ("SPO", "Sports"),
                            ("SG", "Sponsored Grant"),
                            ("RP", "Research Project"),
                            ("CONS", "Consultancy"),
                            ("M_TECH", "M.Tech Students"),
                            ("PH_D", "Ph.D Students"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=6,
                    ),
                ),
                ("top", models.CharField(default="Unknown", max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[("On", "Online"), ("Of", "Offline")], max_length=2
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("Na", "National"), ("In", "International")],
                        max_length=2,
                    ),
                ),
                ("organizer", models.CharField(max_length=100)),
                (
                    "sponsors",
                    models.CharField(
                        choices=[("S", "Sponsored"), ("NS", "Non-Sponsored")],
                        max_length=2,
                    ),
                ),
                (
                    "approval",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("begi_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                ("no_of_days", models.IntegerField()),
                (
                    "proof_enclosed",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("proof_file", models.FileField(upload_to="uploads/fdp_certificate/")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="guided",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nos", models.CharField(max_length=100)),
                ("ens", models.CharField(max_length=100)),
                ("urns", models.CharField(max_length=100)),
                (
                    "eys",
                    models.CharField(
                        choices=[("2023", "2023"), ("2024", "2024"), ("2025", "2025")],
                        max_length=4,
                    ),
                ),
                ("tod", models.CharField(max_length=100)),
                (
                    "visor",
                    models.CharField(
                        choices=[("S", "Supervisor"), ("C", "Co-Supervisor")],
                        max_length=1,
                    ),
                ),
                ("dov", models.DateField()),
                ("noe", models.CharField(max_length=100)),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mooc_course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FDP", "FDP"),
                            ("WKP", "Workshop"),
                            ("CON", "Conference"),
                            ("STTP", "Sttp"),
                            ("SEM", "Seminar"),
                            ("WEB", "Webinar"),
                            ("LS", "Lecture Series"),
                            ("SYM", "Symposium"),
                            ("EE(UG)", "External  Examination(UG)"),
                            ("EE(PG)", "External  Examination(PG)"),
                            ("JOU", "Journal"),
                            ("EL", "Expert Lecture"),
                            ("ET", "Expert Talk"),
                            ("HAT", "Hackathon"),
                            ("TRA", "Training"),
                            ("INT", "Internship"),
                            ("BOS", "BOS"),
                            ("DRC", "DRC"),
                            ("STC", "Short Term Courses"),
                            ("MOOC", "MOOC courses"),
                            ("IP", "Induction Program"),
                            ("EDU", "Education"),
                            ("REA", "Research"),
                            ("SPO", "Sports"),
                            ("SG", "Sponsored Grant"),
                            ("RP", "Research Project"),
                            ("CONS", "Consultancy"),
                            ("M_TECH", "M.Tech Students"),
                            ("PH_D", "Ph.D Students"),
                            ("OTH", "Other"),
                        ],
                        default="MOOC",
                        max_length=6,
                    ),
                ),
                ("timeline", models.CharField(max_length=100)),
                ("noc", models.CharField(max_length=100)),
                (
                    "doc",
                    models.CharField(
                        choices=[
                            ("4", "4 Weeks"),
                            ("8", "8 Weeks"),
                            ("12", "12 Weeks"),
                            ("O", "Other than these"),
                        ],
                        max_length=2,
                    ),
                ),
                ("begi_date", models.DateField()),
                ("end_date", models.DateField()),
                ("offer", models.CharField(max_length=100)),
                (
                    "ctype",
                    models.CharField(
                        choices=[
                            ("G", "Gold"),
                            ("S", "Silver"),
                            ("E", "Elite"),
                            ("SC", "Successfully Completed"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "topper_in",
                    models.CharField(
                        choices=[
                            ("1", "1%"),
                            ("2", "2%"),
                            ("5", "5%"),
                            ("10", "10%"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                ("remarks", models.CharField(max_length=255, null=True)),
                ("proof_file", models.FileField(upload_to="uploads/mooc_certificate/")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="non_teaching_staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=10)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("CSE(AI)", "Computer Science & Engineering(AI)"),
                            ("CSE(DS)", "Computer Science & Engineering(DS)"),
                            ("CSE(IOT)", "Computer Science & Engineering(IOT)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("Lab_no", models.IntegerField()),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("OA", "Office Assistant"),
                            ("TA", "Technical Assistant"),
                            ("A", "Assistant"),
                            ("C", "Clerk"),
                            ("O", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("emp_id", models.IntegerField()),
                (
                    "highest_qual",
                    models.CharField(
                        choices=[
                            ("BT", "B.E. / B.Tech"),
                            ("MT", "M.E. / M.Tech"),
                            ("MS", "M.S."),
                            ("MBA", "MBA"),
                            ("PHD", "Ph.D."),
                            ("PD", "Post-Doctoral Research (Post-Doc)"),
                            ("O", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("university_name", models.CharField(max_length=100)),
                ("pshd", models.IntegerField()),
                (
                    "professional_course",
                    models.CharField(
                        choices=[
                            ("CCNA", "CCNA"),
                            ("HN", "Hardware & Networking"),
                            ("O/A", "O Level/ A level"),
                            ("ACT", "AWS Cloud Technical"),
                            ("VM", "VMware"),
                            ("O", "Other"),
                        ],
                        max_length=4,
                    ),
                ),
                ("pan_no", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("joining_date", models.DateField()),
                ("promotion_date", models.DateField(blank=True, null=True)),
                (
                    "joining_report",
                    models.FileField(
                        upload_to="uploads/non_tech_staff/joining_report/"
                    ),
                ),
                (
                    "offer_letter",
                    models.FileField(upload_to="uploads/non_tech_staff/offer_letter/"),
                ),
                (
                    "higher_degree_certificate",
                    models.FileField(
                        upload_to="uploads/non_tech_staff/higher_degree_certificate/"
                    ),
                ),
                (
                    "salary_slip",
                    models.FileField(upload_to="uploads/non_tech_staff/salary_slip/"),
                ),
                (
                    "certificate",
                    models.FileField(upload_to="uploads/non_tech_staff/certificates/"),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="patents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sop",
                    models.CharField(
                        choices=[("P", "Published"), ("G", "Granted")],
                        default="G",
                        max_length=1,
                    ),
                ),
                ("gi", models.CharField(max_length=100)),
                ("ag", models.CharField(max_length=100)),
                ("top", models.CharField(max_length=100)),
                ("gc", models.CharField(max_length=100)),
                ("pfd", models.DateField(default=datetime.date(2024, 1, 1))),
                ("pd", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "pg",
                    models.CharField(
                        choices=[("I", "Innovation"), ("D", "Design")], max_length=1
                    ),
                ),
                (
                    "ssa",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("details", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("proof_file", models.FileField(upload_to="uploads/patents/")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="research_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noa", models.CharField(max_length=100)),
                ("tob", models.CharField(max_length=100)),
                ("top", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[("Na", "National"), ("In", "International")],
                        max_length=2,
                    ),
                ),
                ("isbn", models.CharField(max_length=100)),
                ("nop", models.CharField(max_length=100)),
                ("pd", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                ("doi", models.CharField(max_length=255)),
                ("lwj", models.CharField(max_length=255)),
                ("aitp", models.CharField(max_length=100)),
                (
                    "ssa",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("details", models.CharField(max_length=255)),
                (
                    "index_by",
                    models.CharField(
                        choices=[
                            ("S", "SCI/SCIE/SSCI"),
                            ("NS", "Scopus"),
                            ("ES", "ESCI"),
                            ("UGC", "UGC"),
                            ("O", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("proof_file", models.FileField(upload_to="uploads/research_book/")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="research_conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noa", models.CharField(max_length=100)),
                ("toc", models.CharField(max_length=100)),
                ("top", models.CharField(max_length=100)),
                ("topc", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[("Na", "National"), ("In", "International")],
                        max_length=2,
                    ),
                ),
                ("isnp", models.CharField(max_length=100)),
                ("nop", models.CharField(max_length=100)),
                ("pd", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                ("doi", models.CharField(max_length=100)),
                ("lwj", models.CharField(max_length=100)),
                ("aitp", models.CharField(max_length=100)),
                (
                    "ssa",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("details", models.CharField(max_length=100)),
                (
                    "index_by",
                    models.CharField(
                        choices=[
                            ("S", "SCI/SCIE/SSCI"),
                            ("NS", "Scopus"),
                            ("ES", "ESCI"),
                            ("UGC", "UGC"),
                            ("O", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("proof_file", models.FileField(upload_to="uploads/research_journal/")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="research_journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noa", models.CharField(max_length=100)),
                ("top", models.CharField(max_length=100)),
                ("noj", models.CharField(max_length=100)),
                ("nop", models.CharField(max_length=100)),
                ("vi", models.CharField(max_length=100)),
                ("pn", models.IntegerField()),
                ("pd", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                ("isnp", models.CharField(max_length=100)),
                ("isno", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[("Na", "National"), ("In", "International")],
                        max_length=2,
                    ),
                ),
                ("doi", models.CharField(max_length=100)),
                ("lwj", models.CharField(max_length=100)),
                ("lap", models.CharField(max_length=100)),
                ("lrsj", models.CharField(max_length=100)),
                ("aiop", models.CharField(max_length=100)),
                (
                    "ssa",
                    models.CharField(choices=[("y", "Yes"), ("N", "No")], max_length=1),
                ),
                ("details", models.CharField(max_length=100)),
                (
                    "index_by",
                    models.CharField(
                        choices=[
                            ("S", "SCI/SCIE/SSCI"),
                            ("NS", "Scopus"),
                            ("ES", "ESCI"),
                            ("UGC", "UGC"),
                            ("O", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "quartile",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                            ("NA", "NA"),
                        ],
                        max_length=2,
                    ),
                ),
                ("proof_file", models.FileField(upload_to="uploads/research_journal/")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FDP", "FDP"),
                            ("WKP", "Workshop"),
                            ("CON", "Conference"),
                            ("STTP", "Sttp"),
                            ("SEM", "Seminar"),
                            ("WEB", "Webinar"),
                            ("LS", "Lecture Series"),
                            ("SYM", "Symposium"),
                            ("EE(UG)", "External  Examination(UG)"),
                            ("EE(PG)", "External  Examination(PG)"),
                            ("JOU", "Journal"),
                            ("EL", "Expert Lecture"),
                            ("ET", "Expert Talk"),
                            ("HAT", "Hackathon"),
                            ("TRA", "Training"),
                            ("INT", "Internship"),
                            ("BOS", "BOS"),
                            ("DRC", "DRC"),
                            ("STC", "Short Term Courses"),
                            ("MOOC", "MOOC courses"),
                            ("IP", "Induction Program"),
                            ("EDU", "Education"),
                            ("REA", "Research"),
                            ("SPO", "Sports"),
                            ("SG", "Sponsored Grant"),
                            ("RP", "Research Project"),
                            ("CONS", "Consultancy"),
                            ("M_TECH", "M.Tech Students"),
                            ("PH_D", "Ph.D Students"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=6,
                    ),
                ),
                ("toe", models.CharField(max_length=100)),
                ("sa", models.CharField(max_length=200)),
                ("doe", models.IntegerField()),
                (
                    "rpt",
                    models.CharField(
                        choices=[
                            ("EE(UG)", "External  Examination(UG)"),
                            ("EE(PG)", "External  Examination(PG)"),
                            ("EBM", "Editorial Board Member"),
                            ("JM", "Jury Member"),
                            ("R", "Reviewer"),
                            ("SC", "Session Chair"),
                            ("E", "Expert"),
                            ("S", "Speaker"),
                            ("KNS", "Key Note Speaker"),
                            ("T", "Trainer"),
                            ("TCM", "Technical Committee Member"),
                            ("DIT", "Delivered Invited Talk"),
                            ("DET", "Delivered Expert Lecture"),
                            ("BM", "BOS Member"),
                            ("DM", "DRC Member"),
                            ("O", "Other"),
                        ],
                        default="O",
                        max_length=6,
                    ),
                ),
                ("begi_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                ("venue", models.CharField(max_length=2550)),
                ("proof_file", models.FileField(upload_to="uploads/resource/")),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sponsored_research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FDP", "FDP"),
                            ("WKP", "Workshop"),
                            ("CON", "Conference"),
                            ("STTP", "Sttp"),
                            ("SEM", "Seminar"),
                            ("WEB", "Webinar"),
                            ("LS", "Lecture Series"),
                            ("SYM", "Symposium"),
                            ("EE(UG)", "External  Examination(UG)"),
                            ("EE(PG)", "External  Examination(PG)"),
                            ("JOU", "Journal"),
                            ("EL", "Expert Lecture"),
                            ("ET", "Expert Talk"),
                            ("HAT", "Hackathon"),
                            ("TRA", "Training"),
                            ("INT", "Internship"),
                            ("BOS", "BOS"),
                            ("DRC", "DRC"),
                            ("STC", "Short Term Courses"),
                            ("MOOC", "MOOC courses"),
                            ("IP", "Induction Program"),
                            ("EDU", "Education"),
                            ("REA", "Research"),
                            ("SPO", "Sports"),
                            ("SG", "Sponsored Grant"),
                            ("RP", "Research Project"),
                            ("CONS", "Consultancy"),
                            ("M_TECH", "M.Tech Students"),
                            ("PH_D", "Ph.D Students"),
                            ("OTH", "Other"),
                        ],
                        max_length=6,
                    ),
                ),
                ("nofa", models.CharField(max_length=100)),
                ("dop", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2025-26", "2025-26"),
                            ("2026-27", "2026-27"),
                            ("2027-28", "2027-28"),
                            ("2028-29", "2028-29"),
                            ("2029-30", "2029-30"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ON", "Ongoing"), ("CM", "Completed")], max_length=2
                    ),
                ),
                (
                    "proof_file",
                    models.FileField(upload_to="uploads/sponsored_research/"),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="firstWebsite.faculty",
                    ),
                ),
            ],
        ),
    ]
