# Generated by Django 5.2.6 on 2025-10-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('college_id', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('student_phone_no', models.CharField(max_length=10)),
                ('parent_phone_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
