# Generated by Django 5.2.6 on 2025-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0002_student_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_directory',
            name='batch',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
