# Generated by Django 5.2.6 on 2025-10-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0003_student_directory_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_directory',
            old_name='email_id',
            new_name='email',
        ),
    ]
