# Generated by Django 5.2.6 on 2025-10-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0004_rename_email_id_student_directory_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.IntegerField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('FA', 'Faculty'), ('AD', 'Admin'), ('SPA', 'Superadmin')], default='FA', max_length=3)),
                ('status', models.CharField(choices=[('R', 'Registered'), ('NR', 'NotRegistered')], default='NR', max_length=2)),
            ],
        ),
    ]
