# Generated by Django 5.2.6 on 2025-10-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0005_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
