# Generated by Django 5.2.6 on 2025-10-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0006_alter_faculty_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_participation_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('On', 'Online'), ('Of', 'Offline')], max_length=2)),
                ('level', models.CharField(choices=[('Na', 'National'), ('In', 'International')], max_length=2)),
                ('organizer', models.CharField(max_length=100)),
                ('sponsors', models.CharField(max_length=100)),
                ('approval', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('begi_date', models.DateField()),
                ('end_date', models.DateField()),
                ('session', models.CharField(max_length=50)),
                ('no_of_days', models.IntegerField()),
                ('proof_enclosed', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('proof_file', models.FileField(upload_to='static/uploads')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
    ]
