# Generated by Django 5.2.6 on 2025-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0007_faculty_participation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_participation_data',
            name='top',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
