# Generated by Django 5.2.6 on 2025-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0008_faculty_participation_data_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_participation_data',
            name='proof_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
