# Generated by Django 5.2.6 on 2025-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0009_alter_faculty_participation_data_proof_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_participation_data',
            name='category',
            field=models.CharField(choices=[('FDP', 'FDP'), ('WKP', 'Workshop'), ('CON', 'Conference'), ('STTP', 'Sttp'), ('SEM', 'Seminar'), ('WEB', 'Webinar'), ('LS', 'Lecture Series'), ('SYM', 'Symposium'), ('OTH', 'Other')], default='OTH', max_length=4),
        ),
    ]
