# Generated by Django 5.2.6 on 2025-10-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0010_faculty_participation_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_participation_data',
            name='proof_file',
            field=models.FileField(upload_to='uploads/fdp_certificate/'),
        ),
        migrations.CreateModel(
            name='mooc_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.CharField(max_length=100)),
                ('noc', models.CharField(max_length=100)),
                ('doc', models.CharField(choices=[('4', '4 Weeks'), ('8', '8 Weeks'), ('12', '12 Weeks'), ('O', 'Other than these')], max_length=2)),
                ('begi_date', models.DateField()),
                ('end_date', models.DateField()),
                ('offer', models.CharField(max_length=100)),
                ('ctype', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('E', 'Elite'), ('SC', 'Successfully Completed')], max_length=2)),
                ('topper_in', models.CharField(choices=[('1', '1%'), ('2', '2%'), ('5', '5%'), ('10', '10%')], max_length=2)),
                ('session', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('proof_file', models.FileField(upload_to='uploads/mooc_certificate/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
    ]
