# Generated by Django 5.2.6 on 2025-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0011_alter_faculty_participation_data_proof_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mooc_course',
            name='topper_in',
            field=models.CharField(choices=[('1', '1%'), ('2', '2%'), ('5', '5%'), ('10', '10%'), ('NA', 'Not Applicable')], max_length=2),
        ),
    ]
