# Generated by Django 5.2.6 on 2025-10-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0012_alter_mooc_course_topper_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_participation_data',
            name='sponsors',
            field=models.CharField(choices=[('S', 'Sponsored'), ('NS', 'Non-Sponsored')], max_length=2),
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eof', models.CharField(choices=[('S', 'Students'), ('TS', 'Teaching Staff'), ('NTS', 'Non-Teaching Staff')], max_length=3)),
                ('topdpo', models.CharField(max_length=100)),
                ('nop', models.IntegerField()),
                ('adcc', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
                ('ct', models.CharField(choices=[('S', 'Sponsored'), ('NS', 'Non-Sponsored')], max_length=2)),
                ('nosa', models.CharField(max_length=100)),
                ('cd', models.CharField(max_length=100)),
                ('begi_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gr', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('gd', models.CharField(max_length=100)),
                ('awpsfooe', models.CharField(max_length=100)),
                ('nossp', models.IntegerField()),
                ('nosmp', models.IntegerField()),
                ('eraipf', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('proof_file', models.FileField(upload_to='uploads/events/')),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
    ]
