# Generated by Django 5.2.6 on 2025-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0013_alter_faculty_participation_data_sponsors_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('FDP', 'FDP'), ('WKP', 'Workshop'), ('CON', 'Conference'), ('STTP', 'Sttp'), ('SEM', 'Seminar'), ('WEB', 'Webinar'), ('LS', 'Lecture Series'), ('SYM', 'Symposium'), ('EE(UG)', 'External  Examination(UG)'), ('EE(PG)', 'External  Examination(PG)'), ('J', 'Journal'), ('EL', 'Expert Lecture'), ('ET', 'Expert Talk'), ('HT', 'Hackathon'), ('T', 'Training'), ('I', 'INTERNSHIP'), ('BOS', 'BOS'), ('DRC', 'DRC'), ('OTH', 'Other')], default='OTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='faculty_participation_data',
            name='category',
            field=models.CharField(choices=[('FDP', 'FDP'), ('WKP', 'Workshop'), ('CON', 'Conference'), ('STTP', 'Sttp'), ('SEM', 'Seminar'), ('WEB', 'Webinar'), ('LS', 'Lecture Series'), ('SYM', 'Symposium'), ('EE(UG)', 'External  Examination(UG)'), ('EE(PG)', 'External  Examination(PG)'), ('J', 'Journal'), ('EL', 'Expert Lecture'), ('ET', 'Expert Talk'), ('HT', 'Hackathon'), ('T', 'Training'), ('I', 'INTERNSHIP'), ('BOS', 'BOS'), ('DRC', 'DRC'), ('OTH', 'Other')], default='OTH', max_length=6),
        ),
    ]
