# Generated by Django 5.2.6 on 2025-10-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0014_events_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('FDP', 'FDP'), ('Workshop', 'Workshop'), ('Conference', 'Conference'), ('STTP', 'Sttp'), ('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Lecture Series', 'Lecture Series'), ('Symposium', 'Symposium'), ('External  Examination(UG)', 'External  Examination(UG)'), ('External  Examination(PG)', 'External  Examination(PG)'), ('Journal', 'Journal'), ('Expert Lecture', 'Expert Lecture'), ('Expert Talk', 'Expert Talk'), ('Hackathon', 'Hackathon'), ('Training', 'Training'), ('Internship', 'Internship'), ('BOS', 'BOS'), ('DRC', 'DRC'), ('Short Term Courses', 'Short Term Courses'), ('MOOC', 'MOOC courses'), ('Induction Program', 'Induction Program'), ('Education', 'Education'), ('Research', 'Research'), ('Sports', 'Sports'), ('Sponsored Grant', 'Sponsored Grant'), ('Research Project', 'Research Project'), ('Consultancy', 'Consultancy'), ('M.Tech Students', 'M.Tech Students'), ('Ph.D Students', 'Ph.D Students'), ('OTH', 'Other')], default='OTH', max_length=25),
        ),
        migrations.AlterField(
            model_name='faculty_participation_data',
            name='category',
            field=models.CharField(choices=[('FDP', 'FDP'), ('Workshop', 'Workshop'), ('Conference', 'Conference'), ('STTP', 'Sttp'), ('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Lecture Series', 'Lecture Series'), ('Symposium', 'Symposium'), ('External  Examination(UG)', 'External  Examination(UG)'), ('External  Examination(PG)', 'External  Examination(PG)'), ('Journal', 'Journal'), ('Expert Lecture', 'Expert Lecture'), ('Expert Talk', 'Expert Talk'), ('Hackathon', 'Hackathon'), ('Training', 'Training'), ('Internship', 'Internship'), ('BOS', 'BOS'), ('DRC', 'DRC'), ('Short Term Courses', 'Short Term Courses'), ('MOOC', 'MOOC courses'), ('Induction Program', 'Induction Program'), ('Education', 'Education'), ('Research', 'Research'), ('Sports', 'Sports'), ('Sponsored Grant', 'Sponsored Grant'), ('Research Project', 'Research Project'), ('Consultancy', 'Consultancy'), ('M.Tech Students', 'M.Tech Students'), ('Ph.D Students', 'Ph.D Students'), ('OTH', 'Other')], default='OTH', max_length=25),
        ),
    ]
