# Generated by Django 5.2.6 on 2025-10-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0018_sponsored_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='research_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noa', models.CharField(max_length=100)),
                ('top', models.CharField(max_length=100)),
                ('noj', models.CharField(max_length=100)),
                ('nop', models.CharField(max_length=100)),
                ('vi', models.CharField(max_length=100)),
                ('pn', models.IntegerField()),
                ('pd', models.DateField()),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
                ('isnp', models.CharField(max_length=100)),
                ('isno', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Na', 'National'), ('In', 'International')], max_length=2)),
                ('doi', models.CharField(max_length=100)),
                ('lwj', models.CharField(max_length=100)),
                ('lap', models.CharField(max_length=100)),
                ('lrsj', models.CharField(max_length=100)),
                ('aiop', models.CharField(max_length=100)),
                ('ssa', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('details', models.CharField(max_length=100)),
                ('index_by', models.CharField(choices=[('S', 'SCI/SCIE/SSCI'), ('NS', 'Scopus'), ('ES', 'ESCI'), ('UGC', 'UGC'), ('O', 'Other')], max_length=3)),
                ('quartile', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('NA', 'NA')], max_length=2)),
                ('proof_file', models.FileField(upload_to='uploads/research_journal/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
    ]
