# Generated by Django 5.2.6 on 2025-10-30 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0020_research_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='research_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noa', models.CharField(max_length=100)),
                ('tob', models.CharField(max_length=100)),
                ('top', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Na', 'National'), ('In', 'International')], max_length=2)),
                ('isbn', models.CharField(max_length=100)),
                ('nop', models.CharField(max_length=100)),
                ('pd', models.DateField()),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
                ('doi', models.CharField(max_length=255)),
                ('lwj', models.CharField(max_length=255)),
                ('aitp', models.CharField(max_length=100)),
                ('ssa', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('details', models.CharField(max_length=255)),
                ('index_by', models.CharField(choices=[('S', 'SCI/SCIE/SSCI'), ('NS', 'Scopus'), ('ES', 'ESCI'), ('UGC', 'UGC'), ('O', 'Other')], max_length=3)),
                ('proof_file', models.FileField(upload_to='uploads/research_book/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
    ]
