# Generated by Django 5.2.6 on 2025-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0021_research_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nof', models.CharField(max_length=100)),
                ('ag', models.CharField(max_length=100)),
                ('top', models.CharField(max_length=100)),
                ('gc', models.CharField(max_length=100)),
                ('pd', models.DateField()),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
                ('pg', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('ssa', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('details', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('proof_file', models.FileField(upload_to='upload/patents/')),
            ],
        ),
    ]
