# Generated by Django 5.2.6 on 2025-11-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0022_patents'),
    ]

    operations = [
        migrations.CreateModel(
            name='guided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nos', models.CharField(max_length=100)),
                ('ens', models.CharField(max_length=100)),
                ('urns', models.CharField(max_length=100)),
                ('eys', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('tod', models.CharField(max_length=100)),
                ('visor', models.CharField(choices=[('S', 'Supervisor'), ('C', 'Co-Supervisor')], max_length=1)),
                ('dov', models.DateField()),
                ('noe', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='patents',
            name='proof_file',
            field=models.FileField(upload_to='uploads/patents/'),
        ),
    ]
