# Generated by Django 5.2.6 on 2025-11-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0023_guided_alter_patents_proof_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='guided',
            name='email',
            field=models.ForeignKey(default='TestCase', on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty'),
        ),
        migrations.AddField(
            model_name='patents',
            name='email',
            field=models.ForeignKey(default='TestCase', on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty'),
        ),
    ]
