# Generated by Django 5.2.6 on 2025-11-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0024_guided_email_patents_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guided',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty'),
        ),
        migrations.AlterField(
            model_name='patents',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty'),
        ),
    ]
