# Generated by Django 5.2.6 on 2025-11-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0025_alter_guided_email_alter_patents_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guided',
        ),
    ]
