# Generated by Django 5.2.6 on 2025-11-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0026_delete_guided'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patents',
        ),
    ]
