# Generated by Django 5.2.6 on 2025-11-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0027_delete_patents'),
    ]

    operations = [
        migrations.CreateModel(
            name='guided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nos', models.CharField(max_length=100)),
                ('ens', models.CharField(max_length=100)),
                ('urns', models.CharField(max_length=100)),
                ('eys', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('tod', models.CharField(max_length=100)),
                ('visor', models.CharField(choices=[('S', 'Supervisor'), ('C', 'Co-Supervisor')], max_length=1)),
                ('dov', models.DateField()),
                ('noe', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nof', models.CharField(max_length=100)),
                ('ag', models.CharField(max_length=100)),
                ('top', models.CharField(max_length=100)),
                ('gc', models.CharField(max_length=100)),
                ('pd', models.DateField()),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
                ('pg', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('ssa', models.CharField(choices=[('y', 'Yes'), ('N', 'No')], max_length=1)),
                ('details', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('proof_file', models.FileField(upload_to='uploads/patents/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
    ]
