# Generated by Django 5.2.6 on 2025-11-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0028_guided_patents'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toe', models.CharField(max_length=100)),
                ('sa', models.CharField(max_length=200)),
                ('doe', models.IntegerField()),
                ('rpt', models.CharField(choices=[('FDP', 'FDP'), ('WKP', 'Workshop'), ('CON', 'Conference'), ('STTP', 'Sttp'), ('SEM', 'Seminar'), ('WEB', 'Webinar'), ('LS', 'Lecture Series'), ('SYM', 'Symposium'), ('EE(UG)', 'External  Examination(UG)'), ('EE(PG)', 'External  Examination(PG)'), ('JOU', 'Journal'), ('EL', 'Expert Lecture'), ('ET', 'Expert Talk'), ('HAT', 'Hackathon'), ('TRA', 'Training'), ('INT', 'Internship'), ('BOS', 'BOS'), ('DRC', 'DRC'), ('STC', 'Short Term Courses'), ('MOOC', 'MOOC courses'), ('IP', 'Induction Program'), ('EDU', 'Education'), ('REA', 'Research'), ('SPO', 'Sports'), ('SG', 'Sponsored Grant'), ('RP', 'Research Project'), ('CONS', 'Consultancy'), ('M_TECH', 'M.Tech Students'), ('PH_D', 'Ph.D Students'), ('OTH', 'Other')], default='OTH', max_length=6)),
                ('begi_date', models.DateField()),
                ('end_date', models.DateField()),
                ('session', models.CharField(choices=[('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=7)),
                ('venue', models.CharField(max_length=2550)),
                ('proof_file', models.FileField(upload_to='uploads/resource/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='firstWebsite.faculty')),
            ],
        ),
    ]
