# Generated by Django 5.2.6 on 2025-11-15 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0029_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patents',
            old_name='nof',
            new_name='gi',
        ),
        migrations.AddField(
            model_name='patents',
            name='pfd',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='patents',
            name='sop',
            field=models.CharField(choices=[('P', 'Published'), ('G', 'Granted')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='patents',
            name='pg',
            field=models.CharField(choices=[('I', 'Innovation'), ('D', 'Design')], max_length=1),
        ),
    ]
