# Generated by Django 5.2.6 on 2025-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0030_rename_nof_patents_gi_patents_pfd_patents_sop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('FDP', 'FDP'), ('WKP', 'Workshop'), ('CON', 'Conference'), ('STTP', 'Sttp'), ('SEM', 'Seminar'), ('WEB', 'Webinar'), ('LS', 'Lecture Series'), ('SYM', 'Symposium'), ('EE(UG)', 'External  Examination(UG)'), ('EE(PG)', 'External  Examination(PG)'), ('JOU', 'Journal'), ('EL', 'Expert Lecture'), ('ET', 'Expert Talk'), ('HAT', 'Hackathon'), ('TRA', 'Training'), ('INT', 'Internship'), ('BOS', 'BOS'), ('DRC', 'DRC'), ('STC', 'Short Term Courses'), ('MOOC', 'MOOC courses'), ('IP', 'Induction Program'), ('EDU', 'Education'), ('REA', 'Research'), ('SPO', 'Sports'), ('SG', 'Sponsored Grant'), ('RP', 'Research Project'), ('CONS', 'Consultancy'), ('M_TECH', 'M.Tech Students'), ('PH_D', 'Ph.D Students'), ('OTH', 'Other')], default='OTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rpt',
            field=models.CharField(choices=[('EE(UG)', 'External  Examination(UG)'), ('EE(PG)', 'External  Examination(PG)'), ('EBM', 'Editorial Board Member'), ('JM', 'Jury Member'), ('R', 'Reviewer'), ('SC', 'Session Chair'), ('E', 'Expert'), ('S', 'Speaker'), ('KNS', 'Key Note Speaker'), ('T', 'Trainer'), ('TCM', 'Technical Committee Member'), ('DIT', 'Delivered Invited Talk'), ('DET', 'Delivered Expert Lecture'), ('BM', 'BOS Member'), ('DM', 'DRC Member'), ('O', 'Other')], default='O', max_length=6),
        ),
    ]
