# Generated by Django 5.2.6 on 2025-11-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0031_resource_category_alter_resource_rpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='non_teaching_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('CSE(AI)', 'Computer Science & Engineering(AI)'), ('CSE(DS)', 'Computer Science & Engineering(DS)'), ('CSE(IOT)', 'Computer Science & Engineering(IOT)')], max_length=8)),
                ('Lab_no', models.IntegerField()),
                ('designation', models.CharField(choices=[('OA', 'Office Assistant'), ('TA', 'Technical Assistant'), ('A', 'Assistant'), ('C', 'Clerk'), ('O', 'Other')], max_length=2)),
                ('emp_id', models.IntegerField()),
                ('highest_qual', models.CharField(choices=[('BT', 'B.E. / B.Tech'), ('MT', 'M.E. / M.Tech'), ('MS', 'M.S.'), ('MBA', 'MBA'), ('PHD', 'Ph.D.'), ('PD', 'Post-Doctoral Research (Post-Doc)'), ('O', 'Other')], max_length=3)),
                ('university_name', models.CharField(max_length=100)),
                ('pshd', models.IntegerField()),
                ('professional_course', models.CharField(choices=[('CCNA', 'CCNA'), ('HN', 'Hardware & Networking'), ('O/A', 'O Level/ A level'), ('ACT', 'AWS Cloud Technical'), ('VM', 'VMware'), ('O', 'Other')], max_length=4)),
                ('pan_no', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('joining_date', models.DateField()),
                ('promotion_date', models.DateField(null=True)),
                ('joining_report', models.FileField(upload_to='uploads/non_tech_staff/joining_report/')),
                ('offer_letter', models.FileField(upload_to='uploads/non_tech_staff/offer_letter/')),
                ('higher_degree_certificate', models.FileField(upload_to='uploads/non_tech_staff/higher_degree_certificate/')),
                ('salary_slip', models.FileField(upload_to='uploads/non_tech_staff/salary_slip/')),
                ('certificate', models.FileField(upload_to='uploads/non_tech_staff/certificates/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstWebsite.faculty')),
            ],
        ),
    ]
