# Generated by Django 5.2.6 on 2025-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0032_non_teaching_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_teaching_staff',
            name='promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
