# Generated by Django 5.2.6 on 2025-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0033_alter_non_teaching_staff_promotion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='aos',
            field=models.CharField(choices=[('AIML', 'Artificial Intelligence & Machine Learning'), ('DIS', 'Data & Information Systems'), ('CN', 'Cybersecurity & Networks'), ('SSD', 'Software Systems & Development'), ('CSA', 'Computer Systems & Architecture'), ('M', 'Mathematics'), ('TCS', 'Theoretical Computer Science'), ('O', 'Other')], default='O', max_length=4),
        ),
        migrations.AddField(
            model_name='faculty',
            name='certificate',
            field=models.FileField(default=None, upload_to='uploads/faculty_documents/certificate/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('AP1', 'Assistant Professor 1'), ('AP2', 'Assistant Professor 2'), ('ASP1', 'Associate Professor 1'), ('ASP2', 'Associate Professor 2'), ('P', 'Professor')], default='AP1', max_length=4),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='hdc',
            field=models.FileField(default=None, upload_to='uploads/faculty_documents/higher_degree_certificate/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='hq',
            field=models.CharField(choices=[('BT', 'B.E. / B.Tech'), ('MT', 'M.E. / M.Tech'), ('MS', 'M.S.'), ('MBA', 'MBA'), ('PHD', 'Ph.D.'), ('PD', 'Post-Doctoral Research (Post-Doc)'), ('O', 'Other')], default='O', max_length=3),
        ),
        migrations.AddField(
            model_name='faculty',
            name='jd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='jr',
            field=models.FileField(default=None, upload_to='uploads/faculty_documents/joining_report/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='norp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='of',
            field=models.FileField(default=None, upload_to='uploads/faculty_documents/offer_letter/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pan_no',
            field=models.CharField(default='AAAEE875AE', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phd_dor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phd_univ',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pshd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='ss',
            field=models.FileField(default=None, upload_to='uploads/faculty_documents/salary_slip/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='univ_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('CSE(AI)', 'Computer Science & Engineering(AI)'), ('CSE(DS)', 'Computer Science & Engineering(DS)'), ('CSE(IOT)', 'Computer Science & Engineering(IOT)')], max_length=8),
        ),
    ]
