# Generated by Django 5.2.6 on 2025-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0034_faculty_aos_faculty_certificate_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='certificate',
            field=models.FileField(default=None, null=True, upload_to='uploads/faculty_documents/certificate/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='hdc',
            field=models.FileField(default=None, null=True, upload_to='uploads/faculty_documents/higher_degree_certificate/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='jr',
            field=models.FileField(default=None, null=True, upload_to='uploads/faculty_documents/joining_report/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='of',
            field=models.FileField(default=None, null=True, upload_to='uploads/faculty_documents/offer_letter/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ss',
            field=models.FileField(default=None, null=True, upload_to='uploads/faculty_documents/salary_slip/'),
        ),
    ]
