# Generated by Django 5.2.6 on 2025-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0035_alter_faculty_certificate_alter_faculty_hdc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phd_univ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
