# Generated by Django 5.2.6 on 2025-11-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0036_alter_faculty_phd_univ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='jd',
            field=models.DateField(),
        ),
    ]
