# Generated by Django 5.2.6 on 2025-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0037_alter_faculty_dob_alter_faculty_jd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
