# Generated by Django 5.2.6 on 2025-12-05 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0038_alter_faculty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dob',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='jd',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
