# Generated by Django 5.2.6 on 2025-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0039_alter_faculty_dob_alter_faculty_jd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_directory',
            name='batch',
            field=models.CharField(choices=[('3CS-A', 'Cs A'), ('3CS-B', 'Cs B'), ('3CS-C', 'Cs C'), ('3CS-D', 'Cs D'), ('3CS-E', 'Cs E'), ('3CS-F', 'Cs F'), ('3CS(AI)-A', 'Cs Ai A'), ('3CS(AI)-B', 'Cs Ai B'), ('3CS(DS)-A', 'Cs Ds A'), ('3CS(IOT)-A', 'Cs Iot A'), ('3CS(IOT)-B', 'Cs Iot B')], default='3CS-F', max_length=10),
        ),
    ]
