# Generated by Django 5.2.6 on 2025-12-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0040_alter_student_directory_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.CharField(default='Address', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
