# Generated by Django 5.2.6 on 2025-12-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0041_faculty_address_faculty_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
