# Generated by Django 6.0 on 2025-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstWebsite', '0043_mooc_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_picture',
            field=models.FileField(default=None, null=True, upload_to='uploads/faculty_documents/profile_picture'),
        ),
    ]
